Cameras:

  # Cameras configurations (all parameters in each camera must be defined)

  camera1: # camera id
    camera: '/dev/video0' # Camera device path
    name: 'Laptop' # Name of the camera
    target_fps: 15 # Target frames per second for the video stream (set it lower than the camera's maximum FPS)
    port: 50000 # Port for the stream server to stream video
    show_fps: False # Whether to show fps for this camera in frames (True/False)
    # following parameters are not mandatory, if not set OpenCV will use default values
    source_format: 'MJPG' # Video pixel format, e.g. 'MJPG' or 'YUYV' (has to be supported by camera)
    width: 640 # Width of the video stream (has to be supported by camera)
    height: 480 # Height of the video stream (has to be supported by camera)
    source_fps: 30 # Actual FPS to read from camera (has to be supported by camera)

  camera2:
    camera: '/dev/video4'
    name: 'Front Door'
    target_fps: 15
    port: 50001
    show_fps: False
  
  # ...

Recordings:  
  save: True # Whether to save camera recordings (True/False)
  # following parameters are required only if save is True
  directory: '../data/recording' # Directory where camera recordings will be saved 
                                 # (absolute path or relative path to where the script is being run from)
  max_days_to_save: 3 # Maximum number of days to keep the saved recordings
  h264_encoder: 'h264_vaapi' # h264 encoder
                           # Software(CPU): libx264, ...
                           # Hardware Acceleration: h264_qsv, h264_amf, h264_nvenc, h264_vaapi, h264_omx, h264_v4l2m2m, ...

Logs:
  save: True # Whether to save logs (True/False)
  # following parameters are required only if save is True
  directory: '../logs' # Directory where logs will be saved
                       # (absolute path or relative path to where the script is being run from)
  max_size: 1024 # Maximum size of each log file in MB
  max_files: 2 # Maximum number of log files to keep
